module.exports.courseData = [
  {
    id: 1,
    name: "Initial Course",
    category: "Programming",
    instructor: "Jane Doe",
    duration: 15,
  },
  {
    id: 2,
    name: "Advanced Course",
    category: "Programming",
    instructor: "John Smith",
    duration: 20,
  },
  {
    id: 3,
    name: "Data Science Course",
    category: "Data Science",
    instructor: "Emily Chen",
    duration: 12,
  },
  {
    id: 4,
    name: "Web Development Course",
    category: "Web Development",
    instructor: "Michael Brown",
    duration: 18,
  },
  {
    id: 5,
    name: "Machine Learning Course",
    category: "Machine Learning",
    instructor: "Sarah Lee",
    duration: 15,
  },
  {
    id: 6,
    name: "Cyber Security Course",
    category: "Cyber Security",
    instructor: "David Kim",
    duration: 10,
  },
  {
    id: 7,
    name: "Database Management Course",
    category: "Database Management",
    instructor: "Jessica Davis",
    duration: 12,
  },
  {
    id: 8,
    name: "Cloud Computing Course",
    category: "Cloud Computing",
    instructor: "Kevin White",
    duration: 15,
  },
  {
    id: 9,
    name: "Networking Course",
    category: "Networking",
    instructor: "Lisa Nguyen",
    duration: 10,
  },
  {
    id: 10,
    name: "Artificial Intelligence Course",
    category: "Artificial Intelligence",
    instructor: "Peter Hall",
    duration: 18,
  },
];
