module.exports = [
  {
    name: "Spaghetti Carbonara",
    description: "A classic Italian pasta dish.",
    preparationTime: "15 minutes",
    cookingTime: "15",
    imageUrl:
      "https://hips.hearstapps.com/hmg-prod/images/carbonara-index-6476367f40c39.jpg?crop=0.888888888888889xw:1xh;center,top&resize=1200:*",
    country: "India",
    veg: true,
    id: 1,
  },
  {
    name: "Chicken Tikka Masala",
    description: "A popular Indian-inspired dish.",
    preparationTime: "20 minutes",
    cookingTime: "30",
    imageUrl:
      "https://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe/recipe-image/2019/05/chickentikkamasala.jpg",
    country: "UK",
    veg: false,
    id: 2,
  },
  {
    name: "Vegetable Stir Fry",
    description: "A quick and easy Chinese-inspired dish.",
    preparationTime: "10 minutes",
    cookingTime: "15",
    imageUrl:
      "https://www.tasteofhome.com/wp-content/uploads/2018/01/Vegetable-Stir-Fry_EXPS_FT20_23742_B02_24_7b.jpg",
    country: "China",
    veg: true,
    id: 3,
  },
  {
    name: "Beef Tacos",
    description: "A flavorful Mexican dish.",
    preparationTime: "20 minutes",
    cookingTime: "30",
    imageUrl:
      "https://www.epicurious.com/images/articlesguides/seasonal/cooking-school/beef-tacos-recipe-120219.jpg",
    country: "Mexico",
    veg: false,
    id: 4,
  },
  {
    name: "Palak Paneer",
    description: "A creamy Indian spinach dish.",
    preparationTime: "20 minutes",
    cookingTime: "30",
    imageUrl:
      "https://www.indianhealthyrecipes.com/wp-content/uploads/2019/03/palak-paneer-recipe.jpg",
    country: "India",
    veg: true,
    id: 5,
  },
  {
    name: "Chicken Fajitas",
    description: "A spicy Mexican dish.",
    preparationTime: "20 minutes",
    cookingTime: "30",
    imageUrl:
      "https://www.epicurious.com/images/articlesguides/seasonal/cooking-school/chicken-fajitas-recipe-120219.jpg",
    country: "Mexico",
    veg: false,
    id: 6,
  },
  {
    name: "Butter Chicken",
    description: "A popular Indian dish.",
    preparationTime: "20 minutes",
    cookingTime: "30",
    imageUrl:
      "https://www.indianhealthyrecipes.com/wp-content/uploads/2019/03/butter-chicken-recipe.jpg",
    country: "India",
    veg: false,
    id: 7,
  },
  {
    name: "Vegetable Curry",
    description: "A flavorful Indian-inspired dish.",
    preparationTime: "20 minutes",
    cookingTime: "30",
    imageUrl:
      "https://www.tasteofhome.com/wp-content/uploads/2018/01/Vegetable-Curry_EXPS_FT20_23742_B03_24_7b.jpg",
    country: "India",
    veg: true,
    id: 8,
  },
  {
    name: "Chicken Quesadillas",
    description: "A Mexican dish with a twist.",
    preparationTime: "20 minutes",
    cookingTime: "30",
    imageUrl:
      "https://www.epicurious.com/images/articlesguides/seasonal/cooking-school/chicken-quesadillas-recipe-120219.jpg",
    country: "Mexico",
    veg: false,
    id: 9,
  },
  {
    name: "Saag Aloo",
    description: "A spicy Indian potato dish.",
    preparationTime: "20 minutes",
    cookingTime: "30",
    imageUrl:
      "https://www.indianhealthyrecipes.com/wp-content/uploads/2019/03/saag-aloo-recipe.jpg",
    country: "India",
    veg: true,
    id: 10,
  },
  {
    name: "Chana Masala",
    description: "A popular Indian chickpea dish.",
    preparationTime: "20 minutes",
    cookingTime: "30",
    imageUrl:
      "https://www.indianhealthyrecipes.com/wp-content/uploads/2019/03/chana-masala-recipe.jpg",
    country: "India",
    veg: true,
    id: 11,
  },
  {
    name: "Fish Tacos",
    description: "A flavorful Mexican dish.",
    preparationTime: "20 minutes",
    cookingTime: "30",
    imageUrl:
      "https://www.epicurious.com/images/articlesguides/seasonal/cooking-school/fish-tacos-recipe-120219.jpg",
    country: "Mexico",
    veg: false,
    id: 12,
  },
  {
    name: "Vegetable Biryani",
    description: "A flavorful Indian rice dish.",
    preparationTime: "25 minutes",
    cookingTime: "40",
    imageUrl:
      "https://www.indianhealthyrecipes.com/wp-content/uploads/2019/03/vegetable-biryani-recipe.jpg",
    country: "India",
    veg: true,
    id: 13,
  },
  {
    name: "Chicken Tikka",
    description: "A popular Indian-inspired appetizer.",
    preparationTime: "20 minutes",
    cookingTime: "30",
    imageUrl:
      "https://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe/recipe-image/2019/05/chickentikka.jpg",
    country: "UK",
    veg: false,
    id: 14,
  },
  {
    name: "Palak Paneer Wrap",
    description: "A creamy Indian-inspired wrap.",
    preparationTime: "20 minutes",
    cookingTime: "30",
    imageUrl:
      "https://www.indianhealthyrecipes.com/wp-content/uploads/2019/03/palak-paneer-wrap-recipe.jpg",
    country: "India",
    veg: true,
    id: 15,
  },
  {
    name: "Beef Fajitas",
    description: "A flavorful Mexican dish.",
    preparationTime: "20 minutes",
    cookingTime: "30",
    imageUrl:
      "https://www.epicurious.com/images/articlesguides/seasonal/cooking-school/beef-fajitas-recipe-120219.jpg",
    country: "Mexico",
    veg: false,
    id: 16,
  },
  {
    name: "Vegetable Soup",
    description: "A comforting Indian-inspired soup.",
    preparationTime: "20 minutes",
    cookingTime: "30",
    imageUrl:
      "https://www.tasteofhome.com/wp-content/uploads/2018/01/Vegetable-Soup_EXPS_FT20_23742_B04_24_7b.jpg",
    country: "India",
    veg: true,
    id: 17,
  },
  {
    name: "Chicken Quesadilla Casserole",
    description: "A Mexican-inspired casserole.",
    preparationTime: "25 minutes",
    cookingTime: "40",
    imageUrl:
      "https://www.epicurious.com/images/articlesguides/seasonal/cooking-school/chicken-quesadilla-casserole-recipe-120219.jpg",
    country: "Mexico",
    veg: false,
    id: 18,
  },
  {
    name: "Saag Paneer",
    description: "A creamy Indian spinach dish.",
    preparationTime: "20 minutes",
    cookingTime: "30",
    imageUrl:
      "https://www.indianhealthyrecipes.com/wp-content/uploads/2019/03/saag-paneer-recipe.jpg",
    country: "India",
    veg: true,
    id: 19,
  },
  {
    name: "Vegetable Korma",
    description: "A flavorful Indian-inspired dish.",
    preparationTime: "20 minutes",
    cookingTime: "30",
    imageUrl:
      "https://www.tasteofhome.com/wp-content/uploads/2018/01/Vegetable-Korma_EXPS_FT20_23742_B05_24_7b.jpg",
    country: "India",
    veg: true,
    id: 20,
  },
];
